version: '3.8'

services:
  # O Banco de Dados (Persistência)
  postgres:
    image: postgres:15
    container_name: encurtador-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: encurtador_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # O Cache (Velocidade)
  redis:
    image: redis:alpine
    container_name: encurtador-cache
    ports:
      - "6379:6379" # Porta padrão do Redis

volumes:
  postgres_data: